site_name: " "
theme:
  name: material
  logo: logo.png
  language: pt
  palette:
    primary: deep purple
    accent: deep purple

extra_css:
  - stylesheets/extra.css


nav:
  - Início: index.md
  - Documentos:
      - Documento de Visão: documentos/doc_visao.md
      - Documento de Arquitetura: documentos/doc_arqui.md
      - Especificação Suplementar: documentos/doc_esp-suplementar.md
      - Termo de Abertura do Projeto: documentos/tap.md
  - Produto:
      - Roadmaps: produto/roadmaps.md
      - Backlog do Produto: produto/product_backlog.md
      - Protótipo de Baixa Fidelidade: produto/prototipo_baixa.md
      - Protótipo de Alta Fidelidade: produto/prototipo_alta.md
      - Testes de usabilidade:
            - Introdução: produto/testesUsabilidade/introducao.md
            - Relatorio 1: produto/testesUsabilidade/relatorio_01.md
            - Relatorio 2: produto/testesUsabilidade/relatorio_02.md
  - Gestão de Projeto:
      - Plano de Comunicação: gestao/plano_comunicacao.md
      - Plano de Gestão de Riscos: gestao/plano_riscos.md
      - Plano de Custos: gestao/plano_custos.md
  - Gestão de Software:
      - Plano de DevOps: gestao/devops.md
      - Plano de Gestão do Repositório: gestao/gcs.md
      - Plano de Qualidade: gestao/qualidade.md
  - Sprints:
      - Sprint 1: sprints/sprint_1.md
      - Sprint 2: sprints/sprint_2.md
      - Sprint 3: sprints/sprint_3.md
      - Sprint 4: sprints/sprint_4.md
      - Sprint 5: sprints/sprint_5.md
      - Sprint 6: sprints/sprint_6.md
  - Apresentações: apresentacoes.md
      
