
site_name: Grupo 4
theme:
  name: material

nav:
    - Home: index.md
    - Documentos:
        - Documento de Visão: documentos/doc_visao.md
        - Especificação Suplementar: documentos/doc_esp-suplementar.md
    - Produto:
        - Roadmaps: produto/roadmaps.md
        - Backlog do Produto: produto/product_backlog.md
        - Protótipo de Baixa Fidelidade: produto/prototipo_baixa.md
    - Sprints:
        - Sprint 1: sprints/sprint_1.md