
site_name: Grupo 4
theme:
  name: material

nav:
    - Home: index.md
    - Documentos:
        - Documento de Visão: documentos/doc_visao.md
    - Produto:
        - Roadmaps: produto/roadmaps.md
    - Sprints:
        - Sprint 0: sprints/sprint_0.md
        - Sprint 1: sprints/sprint_1.md