site_name: " "
theme:
  name: material
  logo: logo.png
  language: pt
  palette:
    primary: deep purple
    accent: deep purple

extra_css:
  - stylesheets/extra.css


nav:
  - Início: index.md
  - Documentos:
      - Documento de Visão: documentos/doc_visao.md
      - Documento de Arquitetura: documentos/doc_arqui.md
      - Especificação Suplementar: documentos/doc_esp-suplementar.md
      - Termo de Abertura do Projeto: documentos/tap.md
  - Produto:
      - Roadmaps: produto/roadmaps.md
      - Backlog do Produto: produto/product_backlog.md
      - Protótipo de Baixa Fidelidade: produto/prototipo_baixa.md
      - Protótipo de Alta Fidelidade: produto/prototipo_alta.md
  - Gestão:
      - Plano de Comunicação: gestao/plano_comunicacao.md
      - Plano de Gestão de Riscos: gestao/plano_riscos.md
  - Sprints:
      - Sprint 1: sprints/sprint_1.md
      - Sprint 2: sprints/sprint_2.md
      - Sprint 3: sprints/sprint_3.md
